// Generated by CoffeeScript 1.9.0
(function() {
  var AssocList;

  AssocList = (function() {
    function AssocList() {
      this.head = {};
      this.tail = this.head;
    }

    AssocList.prototype.getItem = function(key) {
      var item;
      item = this.head;
      while (item = item.next) {
        if (item.key === key) {
          return item.val;
        }
      }
    };

    AssocList.prototype.appendItem = function(key, val) {
      this.tail.next = {
        key: key,
        val: val
      };
      return this.tail = this.tail.next;
    };

    AssocList.prototype.swapItem = function(key, fn) {
      var item;
      item = this.head;
      while (item = item.next) {
        if (item.key === key) {
          item.val = fn(item.val);
          return true;
        }
      }
      return false;
    };

    AssocList.prototype.deleteItem = function(key) {
      var item, nextItem;
      item = {
        next: this.head
      };
      while (item = item.next) {
        if (nextItem = item.next) {
          if (nextItem.key === key) {
            item.next = nextItem.next;
            return nextItem.val;
          }
        }
      }
    };

    AssocList.prototype.iter = function(fn) {
      var item, _results;
      item = this.head;
      _results = [];
      while (item = item.next) {
        if (fn(item)) {
          break;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    AssocList.prototype.toArray = function(fn) {
      var item, ret;
      ret = [];
      item = this.head;
      while (item = item.next) {
        ret.push([item.key, item.val]);
      }
      return ret;
    };

    return AssocList;

  })();

  module.exports = AssocList;

}).call(this);
